# Generated by Django 2.0.3 on 2018-04-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StatPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='expression',
            name='translations',
            field=models.ManyToManyField(related_name='_expression_translations_+', to='vocab.Expression'),
        ),
        migrations.RemoveField(
            model_name='expression',
            name='expression',
        ),
        migrations.AddField(
            model_name='expression',
            name='expression',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statpoint',
            name='srouce_Expression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.Expression'),
        ),
        migrations.AddField(
            model_name='statpoint',
            name='target_Language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.Language'),
        ),
        migrations.AddField(
            model_name='statpoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.User'),
        ),
        migrations.AddField(
            model_name='attemptshistory',
            name='statPoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.StatPoint'),
        ),
        migrations.AddField(
            model_name='expression',
            name='categories',
            field=models.ManyToManyField(to='vocab.Catagory'),
        ),
    ]
