# Generated by Django 2.0.3 on 2018-04-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_auto_20180416_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('correct', models.NullBooleanField()),
                ('attemptsList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.AttemptsHistory')),
            ],
        ),
    ]
