# Generated by Django 2.0.3 on 2018-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_auto_20180604_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passHash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
