# Generated by Django 2.0.3 on 2018-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_expression_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='category',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
