# Generated by Django 2.0.3 on 2018-10-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_auto_20181011_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerattempt',
            name='correct',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='answerattempt',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
