# Generated by Django 2.0.3 on 2018-10-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_auto_20181011_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedWordUserStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.Expression')),
                ('targetLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.User')),
            ],
        ),
    ]
