# Generated by Django 2.0.3 on 2018-10-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_aggregatedworduserstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggrScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField()),
                ('successCount', models.IntegerField()),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.Expression')),
                ('targetLanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='aggregatedworduserstat',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='aggregatedworduserstat',
            name='targetLanguage',
        ),
        migrations.RemoveField(
            model_name='aggregatedworduserstat',
            name='user',
        ),
        migrations.DeleteModel(
            name='AggregatedWordUserStat',
        ),
    ]
