# Generated by Django 2.0.3 on 2018-10-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0011_auto_20181018_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='categories_ser',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
