# Generated by Django 2.0.3 on 2018-11-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0012_expression_categories_ser'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='is_public',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='catagory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vocab.User'),
        ),
    ]
